### ISSUE TITLE
Homebrew installer failing

### ISSUE THREAD

**Issue by joethephish** [bridgedotnet/CLI#14]
On macOS Sierra 10.12.6, see output:

```
computername:~ username$ brew install bridgedotnet/cli/bridge
==> Tapping bridgedotnet/cli
Cloning into '/usr/local/Library/Taps/bridgedotnet/homebrew-cli'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Tapped 2 formulae (31 files, 52.9K)
Error: /usr/local/Library/Taps/bridgedotnet/homebrew-cli/Formula/bridge.rb:108: `${' is not allowed as a global variable name
/usr/local/Library/Taps/bridgedotnet/homebrew-cli/Formula/bridge.rb:108: syntax error, unexpected end-of-input, expecting keyword_end
        scppath="$(dirname "${BASH_SOURCE[0]}")"
                             ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:175:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:100:in `install'
/usr/local/Library/brew.rb:87:in `<main>'
```

Is there another way to install Bridge.net on a Mac?

**Comment by geoffreymcgill** [comment]
Hi @joethephish Thanks for the report. We are investigating.

Looks like it's failing on this line:
https://github.com/bridgedotnet/homebrew-cli/blob/master/Formula/bridge.rb#L108

> Is there another way to install Bridge.net on a Mac?

We have a basic .dmg installer too, which can be downloaded from the following location:

https://github.com/bridgedotnet/Bridge/releases/tag/v17.0.0

Hope this helps.

**Comment by joethephish** [comment]
Ah, great, thanks! I had actually ended up building from source, but that's helpful for future reference :)

**Comment by joethephish** [comment]
Actually, yes I do have Xcode tools installed!

Here's the bash version:

```
computername:~ username$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by fabriciomurta** [comment]
Hello! Thanks for the quick reply! You're using quite a recent copy (as far as OS X and Xcode are concerned).

This really look like homebrew is using another shell during build.

I've then just installed OS X Sierra in a virtual machine here. And guess what, it worked fine. Looks like there's something out of the ordinary in your OS X Sierra installation that prevented it from working.

I didn't install Xcode at all, but my bash interpreter reads the same version you informed (which is surprisingly the same version reported by OS X High Sierra even with Xcode installed).

If you want to get down to the reason it breaks on your side, I can suggest you to `brew install` it with `--debug`, then check if you get any insightful information. Maybe there is something simple we could do to ensure the setup works.

**Comment by fabriciomurta** [comment]
![image](https://user-images.githubusercontent.com/10730372/39783386-3ffd91c2-52eb-11e8-93c3-b264c8549b30.png)

We've just bottled the OS X Sierra build. If you want to give it a try, we'll appreciate your feedback. This should work even if you can't build Bridge from sources with homebrew.

**Comment by joethephish** [comment]
Thanks for the help!

So, I did find that my homebrew was pretty old, which I've now updated, and it got much further, building the dependencies. Unfortunately it failed while building mono, with an error related to me having Xcode 8.3.2 rather than 9.2.

Your post above suggests that you've made a dependency-free build available on Homebrew, is that right? (sorry, I don't know what "bottling" means, I'm a brew-n00b!) I tried running `brew install bridge` a few times, but it seemed to try to build from source each time, wanting to build mono from scratch.

(For completeness, here's the log at the point where it attempts to build mono, though it's clearly unrelated to the current issue...!)

```
==> make all-mono
Last 15 lines from /Users/username/Library/Logs/Homebrew/mono/05.make:
Failed to load /private/tmp/mono--msbuild-20180509-5814-w0165g/Tools/dotnetcli/shared/Microsoft.NETCore.App/1.0.1/libcoreclr.dylib, error: dlopen(/private/tmp/mono--msbuild-20180509-5814-w0165g/Tools/dotnetcli/shared/Microsoft.NETCore.App/1.0.1/libcoreclr.dylib, 1): Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Failed to bind to CoreCLR at '/private/tmp/mono--msbuild-20180509-5814-w0165g/Tools/dotnetcli/shared/Microsoft.NETCore.App/1.0.1/libcoreclr.dylib'
ERROR: Could not restore build tools correctly. See '/private/tmp/mono--msbuild-20180509-5814-w0165g/init-tools.log' for more details.
============= /private/tmp/mono--msbuild-20180509-5814-w0165g/init-tools.log ===========
Running: /private/tmp/mono--msbuild-20180509-5814-w0165g/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003686/dotnet-dev-osx-x64.1.0.0-preview3-003686.tar.gz' to '/private/tmp/mono--msbuild-20180509-5814-w0165g/Tools/dotnetcli/dotnet.tar'
Running: /private/tmp/mono--msbuild-20180509-5814-w0165g/Tools/dotnetcli/dotnet restore "/private/tmp/mono--msbuild-20180509-5814-w0165g/Tools/1.0.27-prerelease-00927-05/project.json" --no-cache --packages /private/tmp/mono--msbuild-20180509-5814-w0165g/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --legacy-packages-directory
============= end of /private/tmp/mono--msbuild-20180509-5814-w0165g/init-tools.log ===========
Initializing BuildTools...
/private/tmp/mono--msbuild-20180509-5814-w0165g/init-tools.sh: line 128: /private/tmp/mono--msbuild-20180509-5814-w0165g/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/init-tools.sh: No such file or directory
ERROR: An error occured when trying to initialize the tools. Please check '/private/tmp/mono--msbuild-20180509-5814-w0165g/init-tools.log' for more details.1
make: *** [all-mono] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/bridgedotnet/homebrew-cli/issues


Error: Your Xcode (8.3.2) is outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.


Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```

**Comment by fabriciomurta** [comment]
Hello! Homebrew team is very strict about some packages' aspects and have been refusing to accept mono set ups to their main stream (specially set ups which includes `msbuild`.

I'd advise you towards getting [mono PKG install from the official mono project website](http://www.mono-project.com/download/stable/#download-mac). For OS X Sierra, I believe that would be the best path to choose. Remember once you install mono from the PKG, you have to restart the shell windows (or re-run the profile scripts) so it adds mono things to the path.

By the way, did you try `bridgedotnet/cli/mono`, or did you just try `mono` from homebrew-core? That's strongly discouraged, at least as far as I know, for they are stuck in old versions. It's been a while since I last checked, and our own `bridgedotnet/cli/mono` has not been updated to 5.10.1 yet. 

The working scenario above used official mono pkg install. Bridge Formula detects whether you have homebrew or pkg install of mono and handles it accordingly (it favors homebrew build if you have both, so remove brew one if you want to stick to pkg install).

**Comment by joethephish** [comment]
Unfortunately I'm currently stuck on mono 4.8.1 because of [a bug in mkbundle](https://bugzilla.xamarin.com/show_bug.cgi?id=51650) so I don't have the choice of updating... yay, dependencies!

Anyway, don't worry! I'm happy with the working version of Bridge CLI that I installed successfully from the DMG, so its all good. Thanks for all the help!
