### ISSUE TITLE
Exception thrown if console is not supported/attached

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/CLI#2]
Running from cygwin, I get this:
```
$ ./bridge.exe new

Installing NuGet package 'Bridge': Error:
The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Bridge.CLI.Program.AddPackage(String folder, String packageName, String version, Boolean restore)
```

(added ex.stacktrace to the message displaying code).
This happens while instantiating the console "spinner".

**Comment by fabriciomurta** [comment]
It seems a good check whether to use or not console colors/spinner is [System.Console.IsOutputRedirected](https://msdn.microsoft.com/en-us/library/system.console.isoutputredirected(v=vs.110).aspx) being false.

If true, colors and animations shouldn't take place. In cygwin it is always true. And from powershell and cmd prompt, it is not (unless, of course, I redirected bridge output using pipes).

Stackoverflow reference: [“The handle is invalid” exception in Visual Studio 2015 test runner](https://stackoverflow.com/questions/31692714/the-handle-is-invalid-exception-in-visual-studio-2015-test-runner)

**Comment by fabriciomurta** [comment]
This should no longer be an issue. Instead of checking against `System.Console.IsOutputRedirected`, we just check if using the related code throws an exception and transparently disables (and caches the decision during the execution) of the ConsoleSpinner class. This should do for most cases.
